# Usa un'immagine base con strumenti di compilazione
FROM debian:bullseye

# Installa le dipendenze necessarie
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    libpcre3 \
    libpcre3-dev \
    libpcre2-dev \
    libssl-dev \
    libtool \
    autoconf \
    automake \
    curl \
    libcurl4-openssl-dev \
    libxml2 \
    libxml2-dev \
    liblua5.3-dev \
    libyajl-dev \
    pkg-config \
    zlib1g-dev \
    libgeoip-dev \
    libxslt1-dev \
    libgd-dev \
    libmailutils-dev \
    wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/nginx/modsec/rules \
             /var/www/certbot \
             /etc/nginx/modules-enabled \
             /etc/nginx/conf.d \
             /var/log/nginx/modsec_audit

# Clona e compila ModSecurity v3
WORKDIR /usr/src
RUN git clone --depth 1 -b v3/master --single-branch https://github.com/SpiderLabs/ModSecurity.git
WORKDIR /usr/src/ModSecurity
RUN git submodule init && git submodule update
RUN ./build.sh && ./configure && make -j$(nproc) && make install

# Clona e compila il modulo Nginx per ModSecurity
WORKDIR /usr/src
RUN git clone --depth 1 https://github.com/SpiderLabs/ModSecurity-nginx.git

# Scarica e compila Nginx con il modulo ModSecurity
ARG NGINX_VERSION=1.25.4
WORKDIR /usr/src
RUN wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz && \
    tar -xvzf nginx-${NGINX_VERSION}.tar.gz
WORKDIR /usr/src/nginx-${NGINX_VERSION}
# Configura Nginx con i moduli richiesti

RUN ./configure \
    --add-dynamic-module=../ModSecurity-nginx \
    --with-http_ssl_module \ 
    --with-http_geoip_module \
    --with-http_image_filter_module \
    --with-http_xslt_module \
    --with-mail \
    --with-stream \
    --with-stream_geoip_module \
    --without-http_rewrite_module \
    --with-pcre \
    --conf-path=/etc/nginx/nginx.conf && \
    make && \
    make install

# RUN ./configure \
#     --add-dynamic-module=../ModSecurity-nginx \
#     --with-http_geoip_module=dynamic \
#     --with-http_image_filter_module=dynamic \
#     --with-http_xslt_module=dynamic \
#     --with-mail=dynamic \
#     --with-stream=dynamic \
#     --with-stream_geoip_module=dynamic \
#     --without-http_rewrite_module \
#     --with-pcre \
#     --conf-path=/etc/nginx/nginx.conf && \
#     make && \
#     make install

# Crea i collegamenti simbolici per i moduli dinamici
# RUN ln -s /usr/share/nginx/modules-available/mod-http-geoip.conf /etc/nginx/modules-enabled/50-mod-http-geoip.conf && \
#     ln -s /usr/share/nginx/modules-available/mod-http-image-filter.conf /etc/nginx/modules-enabled/50-mod-http-image-filter.conf && \
#     ln -s /usr/share/nginx/modules-available/mod-http-xslt-filter.conf /etc/nginx/modules-enabled/50-mod-http-xslt-filter.conf && \
#     ln -s /usr/share/nginx/modules-available/mod-mail.conf /etc/nginx/modules-enabled/50-mod-mail.conf && \
#     ln -s /usr/share/nginx/modules-available/mod-stream.conf /etc/nginx/modules-enabled/50-mod-stream.conf && \
#     ln -s /usr/share/nginx/modules-available/mod-stream-geoip.conf /etc/nginx/modules-enabled/70-mod-stream-geoip.conf

RUN mkdir -p /etc/nginx/modules && \
    cp /usr/src/nginx-${NGINX_VERSION}/objs/*.so /etc/nginx/modules/

# Crea i file di configurazione dei moduli
RUN mkdir -p /etc/nginx/modules-available && \
    echo "load_module modules/ngx_http_modsecurity_module.so;" > /etc/nginx/modules-available/mod-http-modsecurity.conf
    # echo "load_module modules/ngx_http_geoip_module.so;" > /etc/nginx/modules-available/mod-http-geoip.conf && \
    # echo "load_module modules/ngx_http_image_filter_module.so;" > /etc/nginx/modules-available/mod-http-image-filter.conf && \
    # echo "load_module modules/ngx_http_xslt_filter_module.so;" > /etc/nginx/modules-available/mod-http-xslt-filter.conf && \
    # echo "load_module modules/ngx_mail_module.so;" > /etc/nginx/modules-available/mod-mail.conf && \
    # echo "load_module modules/ngx_stream_module.so;" > /etc/nginx/modules-available/mod-stream.conf && \
    # echo "load_module modules/ngx_stream_geoip_module.so;" > /etc/nginx/modules-available/mod-stream-geoip.conf

# Crea i collegamenti simbolici per i moduli dinamici
RUN ln -s /etc/nginx/modules-available/* /etc/nginx/modules-enabled/

# Clona regole di sicurezza di OWASP ModSecurity Core Rule Set
WORKDIR /usr/src
RUN git clone https://github.com/coreruleset/coreruleset.git
RUN mv coreruleset/rules /etc/nginx/modsec/
RUN mv coreruleset/crs-setup.conf.example /etc/nginx/modsec/crs-setup.conf

COPY ./main.conf /etc/nginx/modsec/main.conf
COPY ./modsecurity.conf /etc/nginx/modsec/modsecurity.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

RUN ln -s /usr/local/nginx/sbin/nginx /usr/sbin/nginx

# Esponi le porte 80 (HTTP) e 443 (HTTPS)
EXPOSE 80 443

# Avvia Nginx
CMD ["nginx", "-g", "daemon off;"]