services:
  waf-nginx:
    image: 4ss078/waf-nginx:latest
    build:
      context: ./waf/build
      dockerfile: Dockerfile
    container_name: waf-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./waf/conf.d:/etc/nginx/conf.d
      - ./waf/user-rules:/etc/nginx/modsec/user-rules
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./waf/logs:/var/log/nginx
      - ./www:/var/www/certbot
    restart: unless-stopped
    networks:
      - waf-nginx

  certbot-renew:
    image: 4ss078/certbot:latest
    build:
      context: ./certbot/build
      dockerfile: Dockerfile
    container_name: certbot-renew
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./www:/var/www/certbot
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        while :; do
          certbot renew --webroot -w /var/www/certbot --quiet;
          sleep 12h;
        done
    restart: unless-stopped
    networks:
      - waf-nginx

networks:
  waf-nginx:
    driver: bridge